{
  (
  [
  "
  @root
  "insidersLabel:Meta.tag",|
  
  " InsidersColor: 🔵 ",
 
  "Enforce.Perform.Actions:Auto.Delete",

"Start_Perform_Creation.Of.Delete-Ruleset
§
"Enforce.Delete.Ruleset = True"
)
]
}
